"""llm model config, usage, summary cache, cost controls

Revision ID: 1c51bf55c2be
Revises: f24055dc69e4
Create Date: 2026-09-08 17:01:46.918118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c51bf55c2be'
down_revision: Union[str, Sequence[str], None] = 'f24055dc69e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('provider_type', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('reported_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('run_ref', sa.String(length=200), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_llm_usage_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_events'))
    )
    op.create_index(op.f('ix_llm_usage_events_workspace_id'), 'llm_usage_events', ['workspace_id'], unique=False)
    op.create_index('ix_llm_usage_ws_time', 'llm_usage_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('model_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('provider_type', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('cli_binary', sa.String(length=120), nullable=True),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=True),
    sa.Column('price_input_per_mtok', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_output_per_mtok', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('summarization', 'extraction')", name=op.f('ck_model_configurations_purpose_valid')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_model_configurations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configurations')),
    sa.UniqueConstraint('workspace_id', 'purpose', name=op.f('uq_model_configurations_workspace_id_purpose'))
    )
    op.create_index(op.f('ix_model_configurations_workspace_id'), 'model_configurations', ['workspace_id'], unique=False)
    op.create_table('summary_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('detail_level', sa.String(length=16), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('provider_type', sa.String(length=24), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memory_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_summary_cache_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_summary_cache_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summary_cache')),
    sa.UniqueConstraint('workspace_id', 'person_id', 'cache_key', name=op.f('uq_summary_cache_workspace_id_person_id_cache_key'))
    )
    op.create_index('ix_summary_cache_person', 'summary_cache', ['workspace_id', 'person_id'], unique=False)
    op.create_index(op.f('ix_summary_cache_person_id'), 'summary_cache', ['person_id'], unique=False)
    op.create_index(op.f('ix_summary_cache_workspace_id'), 'summary_cache', ['workspace_id'], unique=False)
    op.add_column('workspace_settings', sa.Column('monthly_spend_limit_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('workspace_settings', sa.Column('monthly_token_limit', sa.Integer(), nullable=True))
    op.add_column(
        'workspace_settings',
        sa.Column('max_job_input_tokens', sa.Integer(), nullable=False, server_default='60000'),
    )
    op.add_column(
        'workspace_settings',
        sa.Column('llm_processing_paused', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_settings', 'llm_processing_paused')
    op.drop_column('workspace_settings', 'max_job_input_tokens')
    op.drop_column('workspace_settings', 'monthly_token_limit')
    op.drop_column('workspace_settings', 'monthly_spend_limit_usd')
    op.drop_index(op.f('ix_summary_cache_workspace_id'), table_name='summary_cache')
    op.drop_index(op.f('ix_summary_cache_person_id'), table_name='summary_cache')
    op.drop_index('ix_summary_cache_person', table_name='summary_cache')
    op.drop_table('summary_cache')
    op.drop_index(op.f('ix_model_configurations_workspace_id'), table_name='model_configurations')
    op.drop_table('model_configurations')
    op.drop_index('ix_llm_usage_ws_time', table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_workspace_id'), table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    # ### end Alembic commands ###
