"""whatsapp inbound connector

Revision ID: 4f7bbfafc134
Revises: de548aea1bbc
Create Date: 2026-09-10 12:24:09.070776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7bbfafc134'
down_revision: Union[str, Sequence[str], None] = 'de548aea1bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('self_identity', sa.Text(), nullable=True),
    sa.Column('self_display_name', sa.Text(), nullable=True),
    sa.Column('self_phone', sa.String(length=32), nullable=True),
    sa.Column('encrypted_session', sa.Text(), nullable=True),
    sa.Column('session_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('inbox_seq', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("provider IN ('whatsapp')", name=op.f('ck_connector_accounts_provider_valid')),
    sa.CheckConstraint("status IN ('unconfigured', 'pairing', 'connected', 'degraded', 'disconnected')", name=op.f('ck_connector_accounts_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_connector_accounts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_connector_accounts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_accounts')),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_connector_accounts_workspace_provider')
    )
    op.create_index(op.f('ix_connector_accounts_workspace_id'), 'connector_accounts', ['workspace_id'], unique=False)
    op.create_table('connector_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('provider_thread_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_estimate', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('history_window', sa.String(length=16), nullable=False),
    sa.Column('history_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('history_complete', sa.Boolean(), nullable=False),
    sa.Column('history_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_thread_id', sa.Uuid(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("history_window IN ('all', 'since_date', 'future_only')", name=op.f('ck_connector_threads_history_window_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['connector_accounts.id'], name=op.f('fk_connector_threads_account_id_connector_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_thread_id'], ['source_threads.id'], name=op.f('fk_connector_threads_source_thread_id_source_threads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_connector_threads_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_threads')),
    sa.UniqueConstraint('account_id', 'provider_thread_id', name='uq_connector_threads_account_thread')
    )
    op.create_index(op.f('ix_connector_threads_account_id'), 'connector_threads', ['account_id'], unique=False)
    op.create_index(op.f('ix_connector_threads_workspace_id'), 'connector_threads', ['workspace_id'], unique=False)
    op.add_column('source_messages', sa.Column('connector_account_id', sa.Uuid(), nullable=True))
    op.add_column('source_messages', sa.Column('provider_message_id', sa.Text(), nullable=True))
    op.add_column('source_messages', sa.Column('direction', sa.String(length=8), nullable=True))
    op.add_column('source_messages', sa.Column('sender_identity', sa.Text(), nullable=True))
    # NOT NULL on an already-populated table needs a server default for the
    # backfill; drop it afterwards so new rows go through the ORM default.
    op.add_column(
        'source_messages',
        sa.Column('content_omitted', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('source_messages', 'content_omitted', server_default=None)
    op.create_check_constraint(
        op.f('ck_source_messages_direction_valid'),
        'source_messages',
        "direction IS NULL OR direction IN ('inbound', 'outbound')",
    )
    op.create_unique_constraint('uq_source_messages_provider_id', 'source_messages', ['workspace_id', 'thread_id', 'provider_message_id'])
    op.create_foreign_key(op.f('fk_source_messages_connector_account_id_connector_accounts'), 'source_messages', 'connector_accounts', ['connector_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('source_participants', sa.Column('suggested_person_id', sa.Uuid(), nullable=True))
    op.add_column('source_participants', sa.Column('source_identity', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_source_participants_suggested_person_id_people'), 'source_participants', 'people', ['suggested_person_id'], ['id'], ondelete='SET NULL')
    op.add_column('source_threads', sa.Column('connector_account_id', sa.Uuid(), nullable=True))
    op.add_column('source_threads', sa.Column('provider_thread_id', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_source_threads_connector_account_id_connector_accounts'), 'source_threads', 'connector_accounts', ['connector_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_source_threads_connector_account_id_connector_accounts'), 'source_threads', type_='foreignkey')
    op.drop_column('source_threads', 'provider_thread_id')
    op.drop_column('source_threads', 'connector_account_id')
    op.drop_constraint(op.f('fk_source_participants_suggested_person_id_people'), 'source_participants', type_='foreignkey')
    op.drop_column('source_participants', 'source_identity')
    op.drop_column('source_participants', 'suggested_person_id')
    op.drop_constraint(op.f('fk_source_messages_connector_account_id_connector_accounts'), 'source_messages', type_='foreignkey')
    op.drop_constraint('uq_source_messages_provider_id', 'source_messages', type_='unique')
    op.drop_constraint(op.f('ck_source_messages_direction_valid'), 'source_messages', type_='check')
    op.drop_column('source_messages', 'content_omitted')
    op.drop_column('source_messages', 'sender_identity')
    op.drop_column('source_messages', 'direction')
    op.drop_column('source_messages', 'provider_message_id')
    op.drop_column('source_messages', 'connector_account_id')
    op.drop_index(op.f('ix_connector_threads_workspace_id'), table_name='connector_threads')
    op.drop_index(op.f('ix_connector_threads_account_id'), table_name='connector_threads')
    op.drop_table('connector_threads')
    op.drop_index(op.f('ix_connector_accounts_workspace_id'), table_name='connector_accounts')
    op.drop_table('connector_accounts')
    # ### end Alembic commands ###
