"""connector thread history bounds

Revision ID: de20cbace194
Revises: 4f7bbfafc134
Create Date: 2026-09-10 13:04:11.188585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de20cbace194'
down_revision: Union[str, Sequence[str], None] = '4f7bbfafc134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector_threads', sa.Column('history_message_cap', sa.Integer(), nullable=True))
    op.add_column('connector_threads', sa.Column('history_synced_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connector_threads', 'history_synced_count')
    op.drop_column('connector_threads', 'history_message_cap')
    # ### end Alembic commands ###
