"""source transcript archive

Revision ID: de548aea1bbc
Revises: 1c51bf55c2be
Create Date: 2026-09-09 11:26:45.446681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de548aea1bbc'
down_revision: Union[str, Sequence[str], None] = '1c51bf55c2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('thread_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_threads_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_threads')),
    sa.UniqueConstraint('workspace_id', 'platform', 'thread_key', name=op.f('uq_source_threads_workspace_id_platform_thread_key'))
    )
    op.create_index(op.f('ix_source_threads_workspace_id'), 'source_threads', ['workspace_id'], unique=False)
    op.create_table('source_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=16), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('new_message_count', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_source_imports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['source_threads.id'], name=op.f('fk_source_imports_thread_id_source_threads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_imports_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_imports'))
    )
    op.create_index(op.f('ix_source_imports_workspace_id'), 'source_imports', ['workspace_id'], unique=False)
    op.create_table('source_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('display_name_normalized', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('unmapped', 'owner', 'person', 'ignored')", name=op.f('ck_source_participants_role_valid')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_source_participants_person_id_people'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['source_threads.id'], name=op.f('fk_source_participants_thread_id_source_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_participants_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_participants')),
    sa.UniqueConstraint('thread_id', 'display_name_normalized', name=op.f('uq_source_participants_thread_id_display_name_normalized'))
    )
    op.create_index(op.f('ix_source_participants_thread_id'), 'source_participants', ['thread_id'], unique=False)
    op.create_index(op.f('ix_source_participants_workspace_id'), 'source_participants', ['workspace_id'], unique=False)
    op.create_table('source_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('sender_name', sa.Text(), nullable=True),
    sa.Column('sender_normalized', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('media_omitted', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("processing_status IN ('awaiting_processing', 'processed', 'skipped')", name=op.f('ck_source_messages_processing_status_valid')),
    sa.ForeignKeyConstraint(['import_id'], ['source_imports.id'], name=op.f('fk_source_messages_import_id_source_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['source_threads.id'], name=op.f('fk_source_messages_thread_id_source_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_messages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_messages')),
    sa.UniqueConstraint('workspace_id', 'thread_id', 'fingerprint', name=op.f('uq_source_messages_workspace_id_thread_id_fingerprint'))
    )
    op.create_index(op.f('ix_source_messages_thread_id'), 'source_messages', ['thread_id'], unique=False)
    op.create_index('ix_source_messages_thread_time', 'source_messages', ['workspace_id', 'thread_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_source_messages_workspace_id'), 'source_messages', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_messages_workspace_id'), table_name='source_messages')
    op.drop_index('ix_source_messages_thread_time', table_name='source_messages')
    op.drop_index(op.f('ix_source_messages_thread_id'), table_name='source_messages')
    op.drop_table('source_messages')
    op.drop_index(op.f('ix_source_participants_workspace_id'), table_name='source_participants')
    op.drop_index(op.f('ix_source_participants_thread_id'), table_name='source_participants')
    op.drop_table('source_participants')
    op.drop_index(op.f('ix_source_imports_workspace_id'), table_name='source_imports')
    op.drop_table('source_imports')
    op.drop_index(op.f('ix_source_threads_workspace_id'), table_name='source_threads')
    op.drop_table('source_threads')
    # ### end Alembic commands ###
