"""initial phase 2 schema

Revision ID: f24055dc69e4
Revises: 
Create Date: 2026-09-08 14:08:19.173764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24055dc69e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('deployment_profile', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug'))
    )
    op.create_table('agent_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_credentials_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_credentials_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_credentials')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_agent_credentials_token_hash')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_agent_credentials_workspace_id_name'))
    )
    op.create_index(op.f('ix_agent_credentials_workspace_id'), 'agent_credentials', ['workspace_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_audit_events_ws_time', 'audit_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('legacy_migration_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_slug', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_manifest_hash', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('backup_ref', sa.Text(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_legacy_migration_runs_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_migration_runs'))
    )
    op.create_table('people',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('birthday_month', sa.Integer(), nullable=True),
    sa.Column('birthday_day', sa.Integer(), nullable=True),
    sa.Column('birthday_year', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('desired_contact_cadence_days', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('connection_level', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('connection_level IS NULL OR (connection_level BETWEEN 1 AND 6)', name=op.f('ck_people_connection_level_range')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_people_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('workspace_id', 'public_id', name=op.f('uq_people_workspace_id_public_id'))
    )
    op.create_index('ix_people_workspace_birthday', 'people', ['workspace_id', 'birthday_month', 'birthday_day'], unique=False)
    op.create_index(op.f('ix_people_workspace_id'), 'people', ['workspace_id'], unique=False)
    op.create_index('ix_people_workspace_name', 'people', ['workspace_id', 'name'], unique=False)
    op.create_table('person_id_sequences',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('last_allocated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_person_id_sequences_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_person_id_sequences'))
    )
    op.create_table('record_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('authority', sa.String(length=24), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_run_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_record_revisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_revisions'))
    )
    op.create_index('ix_record_revisions_entity', 'record_revisions', ['workspace_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_record_revisions_person', 'record_revisions', ['workspace_id', 'person_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_record_revisions_workspace_id'), 'record_revisions', ['workspace_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_workspace_id'), 'sessions', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'editor', 'viewer')", name=op.f('ck_workspace_memberships_role_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_memberships_workspace_id_user_id'))
    )
    op.create_index(op.f('ix_workspace_memberships_user_id'), 'workspace_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.create_table('workspace_settings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('review_threshold', sa.String(length=24), nullable=False),
    sa.Column('allowed_reviewers', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('daily_extraction_time', sa.String(length=5), nullable=False),
    sa.Column('historical_ingestion_default', sa.String(length=24), nullable=False),
    sa.Column('agent_transcript_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_settings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_workspace_settings'))
    )
    op.create_table('facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('local_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date_text', sa.String(length=16), nullable=True),
    sa.Column('date_precision', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('authority', sa.String(length=24), nullable=False),
    sa.Column('related_person_id', sa.Uuid(), nullable=True),
    sa.Column('related_person_public_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("authority IN ('owner_curated', 'agent_curated', 'automatically_extracted')", name=op.f('ck_facts_authority_valid')),
    sa.CheckConstraint("category IN ('Family', 'Work & Education', 'Interests', 'Relationship with User', 'Life Events', 'General Notes')", name=op.f('ck_facts_category_valid')),
    sa.CheckConstraint("confidence IN ('high', 'medium', 'low')", name=op.f('ck_facts_confidence_valid')),
    sa.CheckConstraint("date_precision IS NULL OR date_precision IN ('day', 'month', 'year')", name=op.f('ck_facts_date_precision_valid')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_facts_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_person_id'], ['people.id'], name=op.f('fk_facts_related_person_id_people'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_facts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts')),
    sa.UniqueConstraint('person_id', 'local_id', name=op.f('uq_facts_person_id_local_id'))
    )
    op.create_index(op.f('ix_facts_person_id'), 'facts', ['person_id'], unique=False)
    op.create_index(op.f('ix_facts_workspace_id'), 'facts', ['workspace_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('local_id', sa.String(length=32), nullable=False),
    sa.Column('date_text', sa.String(length=16), nullable=False),
    sa.Column('date_precision', sa.String(length=8), nullable=False),
    sa.Column('occurred_on_latest', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('connection_level', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("authority IN ('owner_curated', 'agent_curated', 'automatically_extracted')", name=op.f('ck_interactions_authority_valid')),
    sa.CheckConstraint("date_precision IN ('day', 'month', 'year')", name=op.f('ck_interactions_date_precision_valid')),
    sa.CheckConstraint('connection_level IS NULL OR (connection_level BETWEEN 1 AND 6)', name=op.f('ck_interactions_connection_level_range')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_interactions_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_interactions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions')),
    sa.UniqueConstraint('person_id', 'local_id', name=op.f('uq_interactions_person_id_local_id'))
    )
    op.create_index(op.f('ix_interactions_person_id'), 'interactions', ['person_id'], unique=False)
    op.create_index('ix_interactions_person_latest', 'interactions', ['person_id', 'occurred_on_latest'], unique=False)
    op.create_index(op.f('ix_interactions_workspace_id'), 'interactions', ['workspace_id'], unique=False)
    op.create_table('person_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('alias_normalized', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_aliases_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_person_aliases_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_aliases')),
    sa.UniqueConstraint('person_id', 'alias_normalized', name=op.f('uq_person_aliases_person_id_alias_normalized'))
    )
    op.create_index(op.f('ix_person_aliases_person_id'), 'person_aliases', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_aliases_workspace_id'), 'person_aliases', ['workspace_id'], unique=False)
    op.create_table('person_contact_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_normalized', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('email', 'phone', 'address', 'messaging')", name=op.f('ck_person_contact_methods_kind_valid')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_contact_methods_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_person_contact_methods_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_contact_methods'))
    )
    op.create_index('ix_person_contact_methods_lookup', 'person_contact_methods', ['workspace_id', 'kind', 'value_normalized'], unique=False)
    op.create_index(op.f('ix_person_contact_methods_person_id'), 'person_contact_methods', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_contact_methods_workspace_id'), 'person_contact_methods', ['workspace_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('related_person_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_relationships_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_person_id'], ['people.id'], name=op.f('fk_relationships_related_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_relationships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    op.create_index(op.f('ix_relationships_person_id'), 'relationships', ['person_id'], unique=False)
    op.create_index(op.f('ix_relationships_workspace_id'), 'relationships', ['workspace_id'], unique=False)
    op.create_table('fact_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('fact_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], name=op.f('fk_fact_sources_fact_id_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_fact_sources_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_sources'))
    )
    op.create_index(op.f('ix_fact_sources_fact_id'), 'fact_sources', ['fact_id'], unique=False)
    op.create_index(op.f('ix_fact_sources_workspace_id'), 'fact_sources', ['workspace_id'], unique=False)
    op.create_table('interaction_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_interaction_sources_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_interaction_sources_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_sources'))
    )
    op.create_index(op.f('ix_interaction_sources_interaction_id'), 'interaction_sources', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_interaction_sources_workspace_id'), 'interaction_sources', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_sources_workspace_id'), table_name='interaction_sources')
    op.drop_index(op.f('ix_interaction_sources_interaction_id'), table_name='interaction_sources')
    op.drop_table('interaction_sources')
    op.drop_index(op.f('ix_fact_sources_workspace_id'), table_name='fact_sources')
    op.drop_index(op.f('ix_fact_sources_fact_id'), table_name='fact_sources')
    op.drop_table('fact_sources')
    op.drop_index(op.f('ix_relationships_workspace_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_person_contact_methods_workspace_id'), table_name='person_contact_methods')
    op.drop_index(op.f('ix_person_contact_methods_person_id'), table_name='person_contact_methods')
    op.drop_index('ix_person_contact_methods_lookup', table_name='person_contact_methods')
    op.drop_table('person_contact_methods')
    op.drop_index(op.f('ix_person_aliases_workspace_id'), table_name='person_aliases')
    op.drop_index(op.f('ix_person_aliases_person_id'), table_name='person_aliases')
    op.drop_table('person_aliases')
    op.drop_index(op.f('ix_interactions_workspace_id'), table_name='interactions')
    op.drop_index('ix_interactions_person_latest', table_name='interactions')
    op.drop_index(op.f('ix_interactions_person_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_facts_workspace_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_person_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_table('workspace_settings')
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_user_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_sessions_workspace_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_record_revisions_workspace_id'), table_name='record_revisions')
    op.drop_index('ix_record_revisions_person', table_name='record_revisions')
    op.drop_index('ix_record_revisions_entity', table_name='record_revisions')
    op.drop_table('record_revisions')
    op.drop_table('person_id_sequences')
    op.drop_index('ix_people_workspace_name', table_name='people')
    op.drop_index(op.f('ix_people_workspace_id'), table_name='people')
    op.drop_index('ix_people_workspace_birthday', table_name='people')
    op.drop_table('people')
    op.drop_table('legacy_migration_runs')
    op.drop_index('ix_audit_events_ws_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_credentials_workspace_id'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
